### ISSUE TITLE
could not find implicit value for parameter marshaller:

### ISSUE THREAD

**Issue by vijaykumargundavarapu** [DanielaSfregola/quiz-management-service#2]
Hi,

I tried to use this portion of code slightly modified for my project but it always gives me the error of could not find implicit value for parameter marshaller:

 case question: Question =>
      **requestContext.complete(StatusCodes.OK, question)**
      killYourself

[error] C:\Projects\Bayer\DashboardReporting\app\services\RestInterface.scala
[error]     customers.map(c => requestContext.complete(StatusCodes.OK, c))
[error]                                               ^
[error] one error found
[error](compile:compileIncremental) Compilation failed
[error] Total time: 277 s, completed Aug 31, 2016 3:07:57 PM
 **could not find implicit value for parameter marshaller: spray.httpx.marshalling.ToResponseMarshaller[(spray.http.StatusCodes.Success, customer)]**

**Comment by DanielaSfregola** [comment]
Hi vijaykumargundavarapu,
the error indicates that spray does not know how to convert your customer class into a json.

For the Question entity in this example, have a look at [QuizProtocol.scala](https://github.com/DanielaSfregola/quiz-management-service/blob/master/spray-akka/src/main/scala/com/danielasfregola/quiz/management/QuizProtocol.scala#L34) and how we have defined how to convert the entity into a json (line 34), you should do something similar for your definition of customer.

Note that this is just one way of doing things. You can also achieve the same using other libraries. For example see [this article](https://danielasfregola.com/2015/08/17/spray-how-to-deserialize-entities-with-json4s/) on how to achieve this using json4s.

I hope this helps!

Cheers,
Daniela
